apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator
  labels:
    app: traffic-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-generator
  template:
    metadata:
      labels:
        app: traffic-generator
    spec:
      containers:
      - name: generator
        image: devops-traffic-gen:latest
        imagePullPolicy: Never
        env:
        - name: API_URL
          value: "http://sample-api.sample-api.svc.cluster.local:80"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
