apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traffic-generator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Girish7010/DevOps-k3s-Assessment-SF-Lab.git
    targetRevision: HEAD
    path: apps/traffic-generator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sample-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
